# Deploy to Firebase on merge to main

name: Deploy to Firebase on merge
on:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_API_URL: https://asia-northeast1-north-c409d.cloudfunctions.net/api

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate Releases
        run: pnpm run generate:releases

      - name: Build
        run: pnpm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NORTH_C409D }}
          channelId: live
          projectId: north-c409d

      - name: Create SA Key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NORTH_C409D }}' > $HOME/gcloud.json

      - name: Deploy Firebase Functions
        run: |
          npm install -g firebase-tools
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
          firebase deploy --only functions --json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcloud.json
